spring:
  application:
    name: book-management

  datasource:
    url: jdbc:mysql://${DATABASE_HOST}/${DATABASE_NAME}
    hikari:
      username: ${DATABASE_USER}
      password: ${DATABASE_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none

  data:
    web:
      pageable:
        default-page-size: 20
        max-page-size: 20
        one-indexed-parameters: true
  cache:
    type: simple

---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: update

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: validate

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:bookdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true

  cache:
    type: none

