name: Deploy to EC2

on:
  push:
    branches:
      - dev
      - feature/**

env:
  BUILD_NUMBER: ${{ github.sha }}-${{ github.run_id }}v

jobs:
  build:
    name : Build Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Github Actions IP
        id: ip
        run: |
          PUBLIC_IP=$(curl -s https://ifconfig.me)
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_ENV

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Add Github Actions IP to Security group
        run: |
          aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port ${{ secrets.SSH_PORT }} --cidr ${{ env.PUBLIC_IP }}/32

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/book-management-dev:${{ env.BUILD_NUMBER }}
            ${{ secrets.DOCKER_USERNAME }}/book-management-dev:latest
          cache-from: type=gha
          cache-to: type=gha, mode=max

      - name: Create .env file
        run: |
          echo "DATABASE_NAME=${{ secrets.DEV_DATABASE_NAME }}" >> .env.dev
          echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> .env.dev
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env.dev
          echo "DATABASE_HOST=${{ secrets.DATABASE_HOST }}" >> .env.dev
          echo "BUILD_NUMBER=${{ env.BUILD_NUMBER }}" >> .env.dev
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> .env.dev
          echo "SPRING_PROFILES_ACTIVE=dev" >> .env.dev

      - name: Transfer files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: ".env.dev,docker-compose.dev.yml,docker-compose.monitor.yml,prometheus.yml"
          target: "~/"
          overwrite: true

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            
            docker compose -f docker-compose.monitor.yml pull
            docker compose --env-file .env.dev -f docker-compose.dev.yml pull
            docker compose -f docker-compose.monitor.yml up -d
            docker compose --env-file .env.dev -f docker-compose.dev.yml up -d

      - name: Health Check & Rollback
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sleep 10
            
            for i in {1..5}; do
              HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}\n" http://localhost:8081/health)
              if [ "$HTTP_STATUS" -eq 200 ]; then
                echo "✅ API is healthy!"
                exit 0
              fi
              sleep 5
            done
            
            echo "❌ API health check failed! Rolling back..."

      - name: Remove Github Actions IP From Security Group
        run: |
          aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port ${{ secrets.SSH_PORT }} --cidr ${{ env.PUBLIC_IP }}/32
